nuxt/vercel-builder

lib/build.js
With a recent change to how `now dev` works, it is important to pass the provided `meta` object to the `download()` function, otherwise it attempts to overwrite the existing files in the working directory.
Related to https://spectrum.chat/zeit/now/is-it-normal-for-now-dev-to-empty-out-all-files-in-my-project~1f21924c-67c3-46d1-8771-52766c3de9ed.
=> Support execution with `now dev`

package.json, yarn.lock
This builder relies on a [private api](https://github.com/zeit/now-builders/blob/39a00c861aec7660a152c05e61ad0740295c8402/packages/now-node-bridge/src/bridge.ts#L105) of `@now/node-bridge` and some changes in `1.2.1 -> 1.2.2` broke the builder.
This PR pins the dependency to fix it.
Fix https://github.com/nuxt/now-builder/issues/66
=> fix: pin @now/node-bridge dependency

lib/build.js
This PR adds support for projects using yarn workspaces (see #102). It forces the workspace module directory to be within the project root directory, using the `--modules-folder` options. (See https://github.com/yarnpkg/yarn/issues/6977.)
From my testing, it shouldn't break any non-workspace-based projects.
=> feat: add support for yarn workspaces

lib/build.js, lib/utils.js
This pull request follows the pattern of the `@now/node` builder to allow installing packages that require Node 10. (This will fix #101, for example.)
However, I'm still struggling with packages like `node-sass` that complain about mismatches of bindings at build-time. The Node 10 bindings are installed correctly, but the `nuxt build` process seems to be using Node 8. My operating hypothesis is that the builder itself is being run by Node 8 - but I'd welcome any help to diagnose or solve.
Closes #101, see also #74.
=> fix: allow installing node 10 dependencies

lib/build.js
This PR aims to implement the required changes to `tsconfig.json` and `now.json` for Typescript based builds (as mentioned in #28), to make it easier to set up a Typescript project using now-builder (as long as the project doesn't use TS nuxt.config.ts, local modules or serverMiddlewares).
=> feat: add required options for typescript projects

lib/build.js
An attempt to address issue #3 and #105, by generating individual routes for each file in the `/static/` directory. To serve static files via CDN (and exclude them from the lambda), set `useGeneratedStaticRoutes` to true in the `@nuxt/now-builder` options in now.json, e.g.:
```json
"builds": [
{
"src": "nuxt.config.js",
"use": "@nuxt/now-builder",
"config": {
"useGeneratedStaticRoutes": true
}
}
]
```
Closes #3, #105
=> feat: expose static files as routes

lib/prepare-cache.js, test/utils/run-build-lambda.js
(It looks like Now silently changed the name of the cache directory from `cachePath` to `prepareCachePath`.)
Closes #111
=> fix: use new object property from Now

lib/build.js
Closes #43 (custom buildPath wasn't being read)
It's possible this may also fix the following reports of 404s:
* https://github.com/nuxt/now-builder/issues/111#issuecomment-529700371
* https://github.com/nuxt/now-builder/pull/106#issuecomment-526937176
=> fix: consume default export of nuxt config file

src/prepare-cache.ts
Now have changed their requirements for the cache. It now must be built relative to `workPath` or `prepareCachePath`. This PR implements this.
In addition, it no longer creates or copies files into the cache directory, as Now do this step subsequent to the running of `prepareCache`.
Closes #133
=> fix: prepare cache against workCache

src/typescript.ts
Noticed the typescript compiling logic was failing with our config that uses a custom srcDir. This change fixes it.
=> fix: use srcDir when compiling build files

src/build.ts
It looks like the [`staticFiles` variable](https://github.com/nuxt/now-builder/blob/master/src/build.ts#L184) is not matching any static assets if the `srcDir` is set in `nuxt.config.ts`.
This PR takes the `srcDir` configuration from the nuxt config & resolves the static assets from its path.
=> fix: use srcDir to retrieve static folder

README.md, src/build.ts, test/build.test.js, test/fixture/www/package.json
If you have been using the `now-node` runtime, you will be familiar
with the `now-build` script. This PR adds support for a prebuild script
using the [same syntax](https://zeit.co/docs/runtimes/?query=now-build#advanced-usage/advanced-node-js-usage/custom-build-step-for-node-js).
=> feat: add support for now-build script

src/build.ts
[Vercel officially supports monorepos](https://vercel.com/blog/monorepos) and can access source files outside the Root Directory (which enables Yarn & Lerna Workspaces). We don't need to set the --modules-folder when using yarn anymore. 
Just enable the "Include source files outside of the Root Directory in the Build Step" option in the Root Directory section within the project settings. 
Vercel projects created after August 27th 2020 23:50 UTC have this option enabled by default.
=> refactor: new vercel monorepo support

README.md, src/build.ts, src/launcher.ts
Running Nuxt and API on the same server is a common use case.
At first, this is not supported. Quoting @danielroe from https://github.com/nuxt/vercel-builder/issues/332#issuecomment-678660418:
> I suspect you might be trying to connect to your serverMiddleware API on server side, which will not work in a serverless environment.
Later in #341, it was suggested that using `$VERCEL_URL` can work around this issue. I previously filed #373 which adds a docs about this workaround. Although it works, it is quite hacky and is unperformant:
- It requires extra configuration.
- It relies on `$VERCEL_URL` to be able to make Nuxt invoke the API on the same deployment.
- In runtime, this causes 2 separate instances of the Lambda function to launch, doubling the response time (due to waiting for 2 cold …
=> feat: add internal server for serverMiddleware

README.md
As per #494 , this PR documents the `memory` and `maxDuration` config properties.
resolves #494
=> docs: add undocumented config options

examples/side-by-side/README.md
From 
With current link (https://github.com/nuxt/vercel-builder/blob/main/examples/side-by-side/side-by-side-example)
To:
With https://github.com/nuxt/vercel-builder/tree/main/examples/side-by-side
=> docs: fixed link to example

README.md
Fixed the name of the npm package body-parser (not bodyParser).
=> docs: README - bodyParser -> body-parser typo

src/prepare-cache.ts
The cache directory is caching files with absolute paths causing deployments with multiple [`builds`](https://github.com/nuxt/vercel-builder/blob/77d99669119c0f319675c1a249328ee1ce105ded/examples/basic/vercel.json#L3) to occasionally fail if they complete in a different order than the previous build.
This PR adds a flag to disable caching until the proper fix can be found.
=> feat: allow disabling cache with `NUXT_CACHE_DISABLED` flag

package.json
This will ensure the latest features are available to deployments,  such as Node.js 16
=> fix: move `@vercel/build-utils` to a devDependency

README.md
The underlying package `@vercel/build-utils` would select the newest available Node.js version unless its specified:
- https://github.com/vercel/vercel/blob/main/packages/build-utils/src/fs/node-version.ts
- https://github.com/vercel/vercel/blob/23dd29e2691823ffbe1b7077cc79f53a47715c1b/packages/build-utils/src/fs/run-user-scripts.ts#L247-L280
=> docs: clarify how Node.js version is selected
